version: 2.1

executors:
  jdk21:
    docker:
      - image: gradle:8.9.0-jdk21
    working_directory: ~/project
    resource_class: small
    environment:
      GRADLE_USER_HOME: ~/.gradle

commands:
  ensure_wrapper:
    steps:
      - run:
          name: Ensure/Bootstrap Gradle Wrapper
          command: |
            set -e
            if [ -x ./gradlew ] && [ -f gradle/wrapper/gradle-wrapper.properties ] && [ -f gradle/wrapper/gradle-wrapper.jar ]; then
              chmod +x ./gradlew
            else
              echo "Gradle wrapper incompleto/ausente; gerando com Gradle instalado no container..."
              if [ -f gradle/wrapper/gradle-wrapper.properties ]; then
                DIST_VER=$(grep -oE 'gradle-[0-9][^/-]*' gradle/wrapper/gradle-wrapper.properties | head -1 | cut -d- -f2)
              fi
              if [ -z "$DIST_VER" ]; then
                DIST_VER=8.9
              fi
              gradle wrapper --gradle-version "$DIST_VER" --no-daemon
              chmod +x ./gradlew
            fi
  restore_gradle_cache:
    steps:
      - restore_cache:
          keys:
            - v1-gradle-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "build.gradle.kts" }}
            - v1-gradle-{{ .Branch }}-
            - v1-gradle-
  save_gradle_cache:
    steps:
      - save_cache:
          key: v1-gradle-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "build.gradle.kts" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

jobs:
  test:
    executor: jdk21
    steps:
      - checkout
      - ensure_wrapper
      - restore_gradle_cache
      - run:
          name: Tests and check
          command: ./gradlew --no-daemon clean check jacocoTestReport
      - save_gradle_cache
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - store_artifacts:
          path: build/reports/jacoco/test
      - store_artifacts:
          path: build/reports/jacoco/test/html

  build:
    executor: jdk21
    steps:
      - checkout
      - ensure_wrapper
      - restore_gradle_cache
      - run:
          name: Build
          command: ./gradlew --no-daemon assemble -x test -x check
      - save_gradle_cache
      - store_artifacts:
          path: build/libs

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
