# .github/workflows/attestation.yml
name: attestation
on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: dist
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/*.jar