name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'
      - '.gitignore'

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2
      - name: Grant execute to wrappers
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi
      - name: Build (includes tests)
        run: |
          if [ -x ./gradlew ] && [ -f ./gradle/wrapper/gradle-wrapper.jar ]; then
            ./gradlew build
          else
            gradle build
          fi
      - name: Rename artifact with Java version
        run: |
          set -e
          JAR=$(ls build/libs/*SNAPSHOT.jar | head -n1)
          BASENAME=$(basename "$JAR" .jar)
          NEW="build/libs/${BASENAME}-java${{ matrix.java }}.jar"
          mv "$JAR" "$NEW"
          echo "RENAMED_JAR=$NEW" >> $GITHUB_ENV
      - name: Generate build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: build/libs/*-java${{ matrix.java }}.jar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-java-${{ matrix.java }}
          path: build/libs/*-java${{ matrix.java }}.jar
