# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [ main ]
    paths-ignore: [ 'README.md','LICENSE.txt','.gitignore' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ 'README.md','LICENSE.txt','.gitignore' ]

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.10.2
          arguments: clean build jacocoTestReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/libs/*.jar

  attest:
    needs: build
    uses: ./.github/workflows/attestation.yml
    with:
      artifact_name: app
